
spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: testproducer
      acks: all
      retries: 10
      properties:
        retry.backoff.ms: 1000

events:
  topicone: topic1
  topictwo: topic2

server:
  port: 9999